language:      c

sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install hunspell
  - sudo apt-get install libhunspell-dev  
install:
  - sh -e /etc/init.d/xvfb start
  - ./travis-tool.sh aptget_install r-cran-xml 
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package trinker/lexicon
  - ./travis-tool.sh github_package trinker/textshape 
  - ./travis-tool.sh github_package jeroenooms/hunspell
script:      ./travis-tool.sh run_tests
after_success:
  - Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success:      change
    on_failure:      change
env:
   global:
     - R_BUILD_ARGS="--resave-data=best" 
     - R_CHECK_ARGS="--as-cran"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1